### ISSUE TITLE
`r#where` vs `where_`, `filter`, and other alternatives

### ISSUE THREAD

**Issue by merlinaudio** [swlkr/ryzz#1]
Hi!

Thanks for building ryzz. This looks like an exceptionally intutive query builder :)

I was wondering if you had considered naming the `where` method something else so the `r#` isn't required.

---

[ormlite](https://crates.io/crates/ormlite) uses

```rs
.where_("age > ?").bind(50)
// or
.where_bind("age > ?", 50)
```

---

[turbosql](https://github.com/trevyn/turbosql) dodges the problem completely and uses

```rs
select!(Person "WHERE name = " name)?;
```

---

[sea-query](https://github.com/SeaQL/sea-query) uses

```rs
.and_where(...)
```

---

[Prisma Client Rust](https://prisma.brendonovich.dev/reading-data/find) does this, which I personally like the most:

```rs
db.users(/* columns to select go in here, i think */)
  .find_first(/* conditions go in here */)
```

**Comment by swlkr** [comment]
I mean it's pretty pedantic, but if the `r#` stuff bothers you that much, you can't be the only one.

I'll have to change `r#where`, `r#in` and `r#as`.

sea-query dropped `or_where` which tells me the api they have makes no sense, they also switched to this:

```rust

let query = Query::select()
     .column(Glyph::Image)
     .from(Glyph::Table)
     .cond_where(
       any()
       .add(Expr::tbl(Glyph::Table, Glyph::Aspect).is_in(vec![3, 4]))
       .add(Expr::tbl(Glyph::Table, Glyph::Image).like("A%")))
     .to_owned();
```

which looks like the enterprise java equivalent of ryzz's api:

```rust
let query = db
    .select(glyph.image)
    .from(glyph)
    .r#where(or(
        r#in(glyph.aspect, vec![3, 4]), 
        like(glyph.image, "A%"))
    );
```

How about this:

- `r#where` -> `where_rows`
- `r#in` -> `is_in`
- `r#as` -> `alias`

**Comment by merlinaudio** [comment]
Sorry, didn't mean to be pedantic 😬

To be honest, r#where might be perfectly fine, it just threw me off the first time I saw it. Thinking about it, IMO it's better than longer alternatives like `where_rows` or `where_bind`

**Comment by swlkr** [comment]
No there is something to it, I usually just let RA autocomplete it and when im writing a query it's `.` and then it shows where as an option, not `r#where` so I think the length of the alternative doesn't matter.

Open source like everything else is 99% marketing, 1% actual thing, so anything that helps ryzz get adoption is worthwhile.

It's a good change

**Comment by swlkr** [comment]
The strategy going forward where rust and sql syntax are the same is to use `{sql}_` instead of `r#{sql}`
